### ISSUE TITLE
Would you consider adopting Go modules?

### ISSUE THREAD

**Issue by alexaandru** [marksalpeter/token#5]
If yes, I'd be happy to provide a PR.

You can read more about it here, esp. the part about releasing V2+ versions: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by marksalpeter** [comment]
@alexaandru very cool! I wasn't aware of the new module system. If you open a pr I'll give it a merge. Just one request: please don't increment to v3 just to add the module system. I know it suggests that in the docs, but thats just silly to me.

**Comment by alexaandru** [comment]
Great then :) You can see the changes here already: https://github.com/alexaandru/token  I introduced it as v2 not v3, and I removed the v2 folder as it is unnecessary with Go modules:

1. those wanting to use v1 can just do a `go get github.com/marksalpeter/token` (which will pull the latest v1.x.y tag)
2. those wanting v2, can do `go get github.com/marksalpeter/token/v2` instead (which will pull the latest v2.x.y tag).

All with the same code, no need for subfolder "forks". The way it works is that it uses the tags - which btw, you will need to adopt going further, they must be under the form v1.2.3 (basically semver, prefixed with a "v"). 

There is a limitation though: only certain versions of Go 1.9, 1.10 are supported (and of course, anything 1.11+): https://github.com/golang/go/wiki/Modules#how-are-v2-modules-treated-in-a-build-if-modules-support-is-not-enabled-how-does-minimal-module-compatibility-work-in-197-1103-and-111

If someone uses a version that it is not "Go modules aware", they will in have pull the latest master (v2) and if they had v1 tokens already, things WILL break badly.

So please let me know what you think, maybe give it a try from my fork and if you like it, I'm more than happy to open PR.

**Comment by marksalpeter** [comment]
@alexaandru I appreciate how clean this is, but I think we should take the second, **"Major Subdirectory"** approach in order to not break backwards compatibility with the people who are currently using this repo, at least until go 1.11 is prolific.

**Comment by alexaandru** [comment]
By all means, you can adopt this at your own pace/as you think is best. Closing this since my initial Q has been answered. If I can help with anything about this in the future, just ping me. Cheers!

**Comment by marksalpeter** [comment]
@alexaandru Finally got around to groking the module system. I'm embarrassed to say it took me this long 😅. Thanks again for the early heads up.

**Comment by alexaandru** [comment]
You're most welcome :) Cheers!
